### ISSUE TITLE
Write Code Documentation

### ISSUE THREAD

**Issue by PatrykHegenberg** [PatrykHegenberg/caesar-transfer#106]
We need to add DocStrings to our source code to make it possible for us and future contributors to get into the source code quickly.

**Summary**
Add DocString to all parts of the flutter and rust code.

**Acceptance Criteria**
Which criteria has to be reached to be accepted
- [x] Human readable
- [x] Correct

**Tasks**
Which tasks are included to add this feature
- [x] Add DocStrings to Rust code
- [x] add DocStrings to Flutter code
- [ ] add DocStrings to Tauri code

**Additional Information**
If the DocStrings are AI generated make sure that the information is correct.
