### ISSUE TITLE
Test the Software

### ISSUE THREAD

**Issue by PatrykHegenberg** [PatrykHegenberg/caesar-transfer#107]
To make sure that everything is working properly, we have to test the software for all supported platforms.

**Summary**
We have to make sure that every part of caesar is working properly on all supported Plattforms.
Because of that we have to test caesar-cli and the gui part.

**Description**
Performe manual tests for all caesar-transfer components or write integration tests, which are performing all necessary tests.

**Acceptance Criteria**
Which criteria has to be reached to be accepted
- [x] all features have to be tested.

**Tasks**
Which tasks are included to add this feature
- [x] test caesar-cli and all of its components (send, receive, serve)
- [x] test caesar-gui and all of its components (send, receive)
