### ISSUE TITLE
Write the presentation handout

### ISSUE THREAD

**Issue by PatrykHegenberg** [PatrykHegenberg/caesar-transfer#108]
According to the course guidelines, we have to write a handout which contains the basic information about our project.

**Summary**
Write a one-page-long handout about our project.
It has to contain information about used languages, frameworks, project structure and management typ, as well as the links to our repository.

**Acceptance Criteria**
Which criteria has to be reached to be accepted
- [x] all project members are in agreement with the handout
- [x] all required information are included

**Tasks**
Which tasks are included to add this feature
- [x] gather all required information
- [x] write the handout

**Dependencies**
Which dependencies are introduced to the project
NONE

**Estimates**
Estimated effort for completion: 5h

**Additional Information**
I would prefer to write the handout with latex, but I'm open for suggestions.

**Comment by PatrykHegenberg** [comment]
The handout was written in Latex and sent before the deadline.
