### ISSUE TITLE
plan and prepare the software presentation

### ISSUE THREAD

**Issue by PatrykHegenberg** [PatrykHegenberg/caesar-transfer#109]
We have to prepare a software presentation for our project.

**Summary**
According to the course guidelines, we have to hold a presentation of our software.
It has to include a presentation of the software itself, as well a walkthrough and description of our code and our project management.
The presentation has to be 45 minutes long.

**Acceptance Criteria**
Which criteria has to be reached to be accepted
- [x] All needed information are part of the presentation
- [x] The presentation time is equally divided between all members.

**Tasks**
Which tasks are included to add this feature
- [x] Plan the presentation
- [x] Prepare the slides
- [x] understand the code, to be able to explain it to others.

**Estimates**
Estimated effort for completion: 5-10h

**Additional Information**
This issue can be split between different members, but everyone has to be able to explain the codebase (at least the rust part)

**Comment by PatrykHegenberg** [comment]
The presentation was created, the parts were divided between the group members and relevant or incomprehensible code parts were discussed.
