### ISSUE TITLE
Perfome a small A/B-Test to decised between the two used frameworks

### ISSUE THREAD

**Issue by PatrykHegenberg** [PatrykHegenberg/caesar-transfer#110]
In order to deside which gui framework we will use, we should performe a small A/B-Test.

**Summary**
Perform an A/B-Test with a small group of end users.

**Acceptance Criteria**
Which criteria has to be reached to be accepted
None

**Tasks**
Which tasks are included to add this feature
- [ ] find a small group of 2-5 users to test different implementations of the frontend.
- [ ] perform a basic feature comparision between the two versions
- [ ] compare speed and ressource usage of the two implementation
- [ ] talk with the other members about the results and discuss the solution for our project.

**Dependencies**
Which dependencies are introduced to the project
None

**Estimates**
Estimated effort for completion: 5h

**Additional Information**
If it's not possible to compare the two implementation, because of missing features or not working on several platforms, I would choose the more feature complete version.

**Comment by PatrykHegenberg** [comment]
We carried out a simplified A/B test as part of the GUI decision.
This included user-friendliness, usability, feature scope and the UX of the GUI.
As developers, we also evaluated the performance, resource utilization and developer friendliness.
The participants were:

- Anna Hegenberg
- Mira Urban
- Manuel Keidel
- Patryk Hegenberg

The results are summarized as follows:

 - The Flutter variant is more user-friendly and easier to use.
- The UX design is better with the Flutter variant.
- The resource utilization seems to be similar, although only one debug build was tested with the Tauri variant.
- The performance seems to be on a similar level
- Developer friendliness is significantly higher with Tauri. 

This led us to the conclusion to use the Flutter variant for the beta release, but to opt for the Tauri variant in the long term.
The design of the Flutter version will be adopted in Tauri and, if possible, all features will be transferred to this version.
